### ISSUE TITLE
[Question] Where is the text for ytsa.thecodeblog.net located? Is it on GitHub?

### ISSUE THREAD

**Issue by maleksware** [melvinchia3636/YouTube-Scraping-API#10]
Is the full version of docs placed on GitHub? If yes, please tell where it is. If no, maybe place it on GH so everyone can change and review it after adding new features.

**Comment by melvinchia3636** [comment]
the source code of the documentation is right here: [Docs Source Code](https://github.com/melvinchia3636/YouTube-Scraping-API/tree/master/docs)
Feel free to make changes to it. The documentation will update automatically after new commit because I'm using the hosting service from [ReadTheDocs](https://readthedocs.org). And for the description of each function and property, the content is right there inside the source code. Feel free to make them better as well.
